### ISSUE TITLE
Show wontfix issues properly

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#140] opened 2019-08-07 06:41 UTC
Right now there is no visual feedback for an issue being in the `wontfix` status. And it's even possible to set it as `wontfix` multiple times. There should be some visual clue (faded out, and grouped maybe) and the button should be disabled, so it's not possible to make the same action again.

**Comment by paveldedik** [comment] 2019-08-07 08:35
We decided to hide issues marked as `wontfix` completely. There is no point displaying it if user decides the issue is not relevant/doesn't make sense for them.

Next step is to allow users to remove the `wontfix` marking from issues. I'm going to create a new issue for that. It has low priority.

**Closed as completed** 2019-08-07 12:09 UTC
